# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SwiftUIProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for SwiftUIProject
	pod 'Moya'
	pod 'ObjectMapper'
  pod 'Moya/RxSwift'
  target 'SwiftUIProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUIProjectUITests' do
    # Pods for testing
  end

end
